### ISSUE TITLE
Registrazioni protette da password di WebEx

### ISSUE THREAD

**Issue by LoGaIta99** [yuri-cinesi/PoliWebex-GUI#16]
Un mio professore ha protetto tutte le registrazioni con una password, il programma stalla indefinitamente se provo a scaricarle.

**Comment by LoGaIta99** [comment]
Ok, no, ogni tanto si incastra, ma provando un po' si accorge della password.

**Comment by LoGaIta99** [comment]
Il programma ha appena fallito il download di tutte le registrazioni protette da password di [questo file](https://github.com/yuyu-19/PoliDL-GUI/files/7070971/Lista.calcolo.numerico.p1.txt), senza richiedermi la password. Allego i log di errore delle prime 6 registrazioni.
[Errori 1.txt](https://github.com/yuyu-19/PoliDL-GUI/files/7076205/Errori.1.txt)

**Comment by yuyu-19** [comment]
Potrebbe volerci un po' per risolvere questo bug, nel frattempo puoi eseguire poliwebex direttamente dalla linea di comando (trovi l'exe in %AppData%\Roaming\WebExRec\Poli-pkg\dist)

**Comment by yuyu-19** [comment]
Controlla se la nuova release risolve il problema.

**Comment by LoGaIta99** [comment]
Per il momento ha segnato come successo un fallimento (quello della prima lezione). Questo è l'output: `Project powered by @sup3rgiu
Features: PoliMi Autologin - Multithreading download
Using aria2 version 1.35.0
Using ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
Video URLs: [
  'https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/c927be37859a483995d22782fb1dd35c'
]
Output Directory: J:\lorga\Videos\Registrazioni Calcolo numerico
Reusing password saved in system's keychain!
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to WebEx login page...
Filling in Servizi Online login form...
We are logged in. 
Got required authentication cookies.
At this point Chrome's job is done, shutting it down...
Start downloading video: https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/c927be37859a483995d22782fb1dd35c
This video is password protected:/Lezione 1 (parte 1)
Please insert the password (or 0 to skip this video): 
Video title is: Lezione 1 (parte 1)
Can't get current video XML-URL. Going to the next one.
These videos have not been downloaded: [
  'https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/c927be37859a483995d22782fb1dd35c'
]
Done!`

Adesso è in stallo mentre prova a scaricare le 3 successive (task manager mi dice che sia il disco sia la rete sono inutilizzate).
Se vuoi ti posso dare la password in privato così puoi provare ad avviare i download anche tu.

**Comment by LoGaIta99** [comment]
Durante la notte ha finito di scaricare la prima lezione, ma si è bloccato lì. Non ha mai segnalato 1 Download completato e non mi ha mai chiesto la password per i video successivi. Inoltre la cartella coi segmenti .ts è ancora al suo posto. Questo è il log dell'operazione (l'ho trovato in %AppData%\WebExRec\Logs):  [PoliDL-Logs_2021-08-31-00-14-23.txt](https://github.com/yuyu-19/PoliDL-GUI/files/7082170/PoliDL-Logs_2021-08-31-00-14-23.txt).

Vuoi che ti passi la password in privato così puoi provare anche tu?

**Comment by LoGaIta99** [comment]
Il problema sembra essere di poliwebex. Questo è l'otput di Poweshell: https://github.com/yuyu-19/PoliDL-GUI/files/7082137/Polidown.txt.

**Comment by yuyu-19** [comment]
> 
> 
> Durante la notte ha finito di scaricare la prima lezione, ma si è bloccato lì. Non ha mai segnalato 1 Download completato e non mi ha mai chiesto la password per i video successivi. Inoltre la cartella coi segmenti .ts è ancora al suo posto. Questo è il log dell'operazione (l'ho trovato in %AppData%\WebExRec\Logs): [PoliDL-Logs_2021-08-31-00-14-23.txt](https://github.com/yuyu-19/PoliDL-GUI/files/7082170/PoliDL-Logs_2021-08-31-00-14-23.txt).
> 
> Vuoi che ti passi la password in privato così puoi provare anche tu?

Si grazie, per favore inoltrami la password in privato.

**Comment by yuyu-19** [comment]
Risolto nell'ultima release.
