### ISSUE TITLE
Parsing Length

### ISSUE THREAD

**Issue by DavideTommy** [yuri-cinesi/PoliWebex-GUI#17]
Problemi: confersion from string "" to Integer not valid quando l'html passato è corretto, idem per il percorso. Nessuno spazio. oppure "lenght cannot be less than 0" parameter name:length" 
![image](https://user-images.githubusercontent.com/15313107/132596973-1c3d1122-5176-419f-a2bb-6fc9f1a97888.png)

**Comment by yuyu-19** [comment]
Risolto, era un errore con corsi che non hanno orari definiti.

**Comment by DavideTommy** [comment]
Eeeh immaginavo! Ho un corso dell'unipv ancora a muzzo... Gran bel lavoro comunque, davvero complimenti!

On Sep 15, 2021 21:08, yuyu-19 ***@***.***> wrote:

Risolto, era un errore con corsi che non hanno orari definiti.
