### ISSUE TITLE
No files in Local mode

### ISSUE THREAD

**Issue by DavideTommy** [yuri-cinesi/PoliWebex-GUI#18]
Impossible to see html files in files selection. Only typing name in name bar they appear.
![image](https://user-images.githubusercontent.com/15313107/132637447-b0addc59-9144-43a2-9c11-a2bf4d05d849.png)

**Comment by yuyu-19** [comment]
Fix will be rolled out in the upcoming release.

EDIT: Actually not the upcoming one but the one after that - I need to take a look at the entire local mode to see everything that might've broke, so it will take some time. Next release will only contain the download mode fixes.
