### ISSUE TITLE
Problema download intero corso

### ISSUE THREAD

**Issue by mind-overflow** [yuri-cinesi/PoliWebex-GUI#19]
Ciao! Scusa la domanda probabilmente stupida, ma non riesco a capire come scaricare un intero corso da WeBeep.  
Copiando il link di recman sul portale dei servizi online, il programma restituisce un errore:  
> Rilevato link recman. Per scaricare video dall'archivio registrazioni, devi andare nella pagina webeep del tuo corso, e copiare il link \"Archivio registrazioni\" cliccando con il tasto destro.  
  
Cosa che ho provato a fare: vado su webeep.polimi.it, apro un corso, e poi faccio click destro e copio il link dell'archivio. Il link è del tipo:  
```
https://webeep.polimi.it/mod/url/view.php?id=XXXXX
```  
Chiaramente, però, non va bene, perché questo è un link interno a webeep, che poi rimanda al link corretto (che purtroppo però reindirizza subito anche a recman, quindi bisogna seguire la lista di reindirizzamenti per prendere quello giusto). Ho trovato un corso in cui il prof ha incollato direttamente il link giusto, ovvero del tipo:  
```
https://aunicalogin.polimi.it/aunicalogin/getservizio.xml?id_servizio=XXXX&c_classe_webeep=XXXXXX-YYY
```  

Copiando questo link in PoliDL, mi dice:  
> Rilevato link recman. Premi OK per avviare l'estrazione dei link (potrebbe richiedere qualche minuto).  
  
Clicco ok, e mi si apre una finestra Chromium automatizzata; faccio il login guidato con SPID e infine mi si apre il sito Webex del poli. Dopo qualche secondo PoliDL apre la pagina di Recman, ed è qui che il tutto si ferma.  
  
Il browser rimane fermo su Recman per un po' di tempo, dopodiché si chiude ma su PoliDL non succede nulla. Le finestre aperte rimangono fisse e non cliccabili; l'unico modo di fermarlo è terminare il processo. Il programma non è in crash, è semplicemente non responsivo, come se stesse ancora aspettando dei risultati da Chromium.  
  
Probabilmente sto sbagliando qualcosa io, però non riesco a capire dove...  
Grazie e scusa il disturbo :)

**Comment by yuyu-19** [comment]
Risolto, inoltre dovresti poter inserire direttamente il link webeep del corso (https://webeep.polimi.it/course/view.php?id=[ID]) per scaricare le registrazioni.

**Comment by mind-overflow** [comment]
Perfetto! Grazie mille, ora funziona benissimo copiando direttamente il link del corso dalla home di WeBeep.
