### ISSUE TITLE
Reiterazione issue #6

### ISSUE THREAD

**Issue by mind-overflow** [yuri-cinesi/PoliWebex-GUI#20]
Ciao!  
Scusa nuovamente per il disturbo, ma ho notato che nella issue #6 era stato proposto di skippare il download dei file già esistenti, che teoricamente è stato implementato nella v0.9... Oggi però ho scaricato in bulk un corso da WeBeep (grazie mille per il fix della #19!); qualche download è fallito e quindi ho fatto ripartire il tutto, ma mi ha scaricato di nuovo anche le lezioni già esistenti, aggiungendo ".1" alla fine del nome del file...  
Sarebbe possibile apportare questa modifica? Sarebbe molto comodo anche per aggiornare i corsi durante il semestre, scaricando per esempio le nuove lezioni ogni fine settimana. Grazie mille ancora!

**Comment by yuyu-19** [comment]
Il problema è che non c'è nessun modo di verificare se un download è stato completato o se si è interrotto, ed è per quello che vengono ri-scaricati.

Se alcuni download sono falliti, puoi semplicemente cliccare "Ulteriori informazioni" di fianco al numero di quelli falliti, e c'è un tasto per salvare un txt con tutti i link che non sono stati scaricati.

Vedo di aggiungere una checkbox per scegliere se riscaricarli o meno.

**Comment by mind-overflow** [comment]
Capisco, non ho guardato a fondo il source, ma non sarebbe possibile controllare il completamento di un download dalla dimensione del file? Se quello scaricato ha la stessa lunghezza in byte di quello da scaricare (sperando che WebEx annunci le dimensioni dei file), allora si può presumere che il download sia stato completato.  
  
Chiaramente potrebbe essere un download della giusta dimensione ma corrotto, ma in ogni caso non credo che siano implementati controlli di integrità, perciò anche riscaricandolo 3 volte si può sempre incorrere nel rischio di avere corruzioni.  
  
Così, era giusto un'idea, magari è semplice da implementare o magari non si può; io la propongo.     
  
Grazie mille per l'ottimo lavoro!

**Comment by yuyu-19** [comment]
Implementato in v1.4
